os: linux
language: cpp
compiler: gcc
dist: xenial
matrix:
  fast_finish: true
  include:
    ### Archlinux QtWebEngine
    - env: DOCKER=archlinux-webengine QUTE_BDD_WEBENGINE=true
      services: docker
script:
    - qmake
    - make
